{% set version = "1.1-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fastmatch
  version: {{ version|replace("-", "_") }}

source:
  fn: fastmatch_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/fastmatch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastmatch/fastmatch_{{ version }}.tar.gz
  sha256: 10b147ff26df1bda6f41e13ffc8b5740309a01838c78e1902404832da64f4d66

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('fastmatch')"           # [not win]
    - "\"%R%\" -e \"library('fastmatch')\""  # [win]

about:
  home: http://www.rforge.net/fastmatch
  license: GPL-2.0-only
  summary: Package providing a fast match() replacement for cases that require repeated look-ups. It is slightly faster that R's built-in match() function on first match against a table, but extremely fast on any subsequent lookup as it keeps the hash table in memory.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
