{% set version = "1.1-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fastmatch
  version: {{ version|replace("-", "_") }}

source:
  fn: fastmatch_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/fastmatch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastmatch/fastmatch_{{ version }}.tar.gz
  sha256: 9a914cac9c1ea2984bd44eebe421e1636504907a8064ae26347fe3ec2b9bd56b

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('fastmatch')"           # [not win]
    - "\"%R%\" -e \"library('fastmatch')\""  # [win]

about:
  home: http://www.rforge.net/fastmatch
  license: GPL-2.0-only
  summary: Package providing a fast match() replacement for cases that require repeated look-ups. It is slightly faster that R's built-in match() function on first match against a table, but extremely fast on any subsequent lookup as it keeps the hash table in memory.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
