appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: igoFp5aHKoW/LRN1fgYCXWSvGv9Ilbuf6GhXdDpnPAlyh5T+4CUBoXmQaLnF02nTjxZfxkh/rnMPD86nBgztwvAiwCcHVAFEfIE7N4IqMrbz+vGPNj1x1WgR5cK61GzYRY65i9R1jlquHkDDDHip3miECY7cn7p9fKHTmxx1s3EypoOmfN2g7EgL3TduxAP1lv7NJdDz69NmoLcsztFhYM4OzdCJ5ad8wzVkgD2JHwCjA5y/O7LMvbkdyL0ECQlSzOlhdUjUeF/OQ5x/hEgq0YlNRKOQByA5wlWxSb9UADl7zq8Ne40mut6XfwlxAvIzXXjKiEuJwT6tbQNFWVp+THImTNrYCUvMkXPSlHPpnx8HXhoK+Z7vvMj7PoPRCn6+503naDqK4GalPMuTn7peqjVxYRgS7D0Rt8gt7hpMQnD8jnrE8trK0kBqvQnr2y49gnBSFlxGVADTCZPQPoAmb5sUTghEnIzRX/1Cz6GtGvrJYVuZmLNZhgMMHVWtkLlNWDzS0qLiHvGOsLah8nTq5e/J95ZW/1isgCENPFNWFuUYM3q8BSse1cu3JaN6urxaDDG0KaGtwA8ak6OKel63DtR1jCXYaDIqEmsyGIjwcDRQwieKnqqqa3GENZROVLYWOrtV3wFNfvHt5vtIlm78+xX+Y/qdwuBBxF3KoJsoy2Y=}
