travis:
  secure:
    BINSTAR_TOKEN: XlMIjCUxi3U9/NndT0RShcL6RiNJ6XR3TI3JwLCXCFV/2sdShsMmrSgPLmT78jlg0q+QcjdQSnRhB6P9/Lo33L2SCMzVnlV8KwhALlgyG1g3U+/wwAaYulE+YBatngjSnx33/g8onX90Ohgzhjwhretlzo9gL52iZG/uTco7iIdbH9IVPoU8BLmjCd7YsFaXhcgWGK6d9Y6YISSmOcDb1vY+JxRN4wCcaxkB7pvUdqoMnYXxxtOGkrG9zQAtHwz4XC7q4QUEwRUrtLArFEX6EaW3UsblYMDKfAW1eMIE93IWslBkSuB+vlY40UQ3DUwU8Q5ApOqoiEEUFN3B3PO28/mYkHEZHuP4UKNxBlox8VTfBVdFW0iPke8umMUb1vxxlf34YBO/Dlw9Yeyxp11HJpoDRwZCEcFTtsTHnG+4Y6wU0eTc8daLD1d3BgBlr2Ww/T+Bwl5+3ikqhLNpDWF2Pd8Ktbuns1DA7nLcNfLhqVsrRX0E1+Dj1N/6AYmc+6WHsmhysj1qV1excKNMgrm1a78JUHFeEBrwYTBHPZ4j55lyaKWJuMFjOamcwa/PIsfiE8IeGPWswPmT2WyVkMnTi8GwtbZLPACo+0reR9/+/iXBBoCcnyVJEJ3hOkqWecl899QdHYMOWn/KZBEY2IqPvcaTNWhg+Wd+eLXmDjBiT3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
