travis:
  secure:
    BINSTAR_TOKEN: MBH+T9GWMEdwPkrbsM9+u5QzNrLxED5jxzHw369pElZBb5KYcVw4SU78FMDMWV24ai6kesiwAHQYAXzFjXJo3Q14FGXjLq0Lxf9jBY2K2d5grOIXpnlx069HQuE/D5BxjHutSy4WmAjwSh+y+wIOLjsb7Kn699i639oeNe5RUTjcEKPepL7Iw31P4HQ/2cLOaN8Ap+Fj8RukQdCRGjIbQ2CZR4YyH95oy6+ofEhS6wibAAn6Iy82em6Du3BY29UNxnnuiLftTRzid7nb/SQIOJT9ALAm7kez1PLF7F6vJmXn4+8SJipkPlN5FFljNlu9daggtP1DH01IbQR+kcGnjQKGxVw1Xm4S9mQhSg6a9MOlQVCw4yc8AAIy/Gtph+j+kt8ZJmbU7JQmbio12N8mkGZ9+dngoXEpMEEzvZOfAKMD7DbHesYDwNpF7bY8oP+p2USC1SWPzsM7cjUMKT5yx2CqgDcE4KyPtX5fLn7wIEGcRWLrtFifA4zDDqpYAxfwVWB4G26A97yuYPVXQF+8c6aps803fqWMFwTe88DSyKjYCR36lMY3gatn/ncxKxqRX+dgSMtbPwC6/k1T+rVvwhb7tnLhpHqRkhFMAoW67R6Q7omFDU+mvh6YzIM8QBJG83qHQBF6X+i+gW1VrYwouuckZBC4EPiM5WS/yWSJOsI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
